apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx-headless
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx-headless

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-headless
spec:
  serviceName: nginx-headless
  replicas: 3
  selector:
    matchLabels:
      app: nginx-headless
  template:
    metadata:
      labels:
        app: nginx-headless
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx-headless
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
        annotations:
          volume.alpha.kubernetes.io/storage-class: ""
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
