apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
