apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
spec:
  containers:
    - image: nginx:alpine
      name: nginx-hostpath
      volumeMounts:
        - mountPath: /hostpath
          name: hostpath
  volumes:
    - name: hostpath
      hostPath:
        path: /home/user/kube/scratch/volume
        type: Directory
